//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitou_School_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentsPerStudentsPerCourse
    {
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AssignmentId { get; set; }
        public string Titlos { get; set; }
        public string Description { get; set; }
    }
}
