//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitou_School_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfStudent
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int TuitionFees { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
    }
}
